# Dynamic tools generated by AI
"""
DRAKBEN Dynamic Modules Package.

Bu klasör Singularity AI Engine tarafından runtime'da
otomatik olarak üretilen Python modüllerini içerir.

Kullanım:
    - Singularity.synthesize_tool() çağrıldığında yeni tool
      bu klasöre .py dosyası olarak yazılır
    - tool_registry otomatik olarak yeni tool'u yükler
    - Hot-reload ile agent yeniden başlatılmadan tool kullanılabilir

Not: Bu klasör başlangıçta boştur, tool'lar runtime'da oluşturulur.
"""
